import { Geist, Geist_Mono } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import BootstrapClient from "./BootstrapClient";
import "@fortawesome/fontawesome-free/css/all.min.css";
import "../styles/style.css";
import "./globals.css";

// import "../styles/animate.min.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
         <BootstrapClient />
        {children}
      </body>
    </html>
  );
}
